export const mockData = [
  {
    id: '0001',
    author: 'Alan Friedman',
    title: 'Qualcomm says Apple\'s iOS update fix shouldn\'t prevent US ban on the iPhone - Phone Arena',
    description: 'Qualcomm filed a document with the U.S. ITC that says Apple\'s iOS workaround that removes any trace of unlicensed Qualcomm IP should not prevent the ITC from banning the sales and imports of certai...',
    url: 'https://www.phonearena.com/news/ITC-to-rule-March-26th-on-possible-U.S.-iPhone-ban_id113823',
    urlToImage: 'https://bloximages.newyork1.vip.townnews.com/richmond.com/content/tncms/assets/v3/editorial/0/de/0de6865d-274b-58a8-a726-863c20ab47d8/5c6c96de53ee2.image.jpg?resize=430%2C284',
    publishedAt: '2019-02-20T00:00:00Z',
    content: 'Apple has a history of disobeying court orders (eg, the UK case against Samsung). Apple probably think it owns the 9th circuit, but Trump isn\'t exactly Obama and is not going to dance to Apple\'s tune. Apple needs spanking and needs to understand that it\'s not…',
  },
  {
    id: '0002',
    author: 'Alan Friedman',
    title: 'Qualcomm says Apple\'s iOS update fix shouldn\'t prevent US ban on the iPhone - Phone Arena',
    description: 'Qualcomm filed a document with the U.S. ITC that says Apple\'s iOS workaround that removes any trace of unlicensed Qualcomm IP should not prevent the ITC from banning the sales and imports of certai...',
    url: 'https://www.phonearena.com/news/ITC-to-rule-March-26th-on-possible-U.S.-iPhone-ban_id113823',
    urlToImage: '//i-cdn.phonearena.com/images/article/113823-two/Qualcomm-says-Apples-iOS-update-fix-shouldnt-prevent-U.S.-ban-on-the-iPhone.jpg',
    publishedAt: '2019-02-20T00:00:00Z',
    content: 'Apple has a history of disobeying court orders (eg, the UK case against Samsung). Apple probably think it owns the 9th circuit, but Trump isn\'t exactly Obama and is not going to dance to Apple\'s tune. Apple needs spanking and needs to understand that it\'s not…',
  },
  {
    id: '0003',
    author: 'Alan Friedman',
    title: 'Qualcomm says Apple\'s iOS update fix shouldn\'t prevent US ban on the iPhone - Phone Arena',
    description: 'Qualcomm filed a document with the U.S. ITC that says Apple\'s iOS workaround that removes any trace of unlicensed Qualcomm IP should not prevent the ITC from banning the sales and imports of certai...',
    url: 'https://www.phonearena.com/news/ITC-to-rule-March-26th-on-possible-U.S.-iPhone-ban_id113823',
    urlToImage: 'https://bloximages.newyork1.vip.townnews.com/richmond.com/content/tncms/assets/v3/editorial/0/de/0de6865d-274b-58a8-a726-863c20ab47d8/5c6c96de53ee2.image.jpg?resize=430%2C284",',
    publishedAt: '2019-02-20T00:00:00Z',
    content: 'Apple has a history of disobeying court orders (eg, the UK case against Samsung). Apple probably think it owns the 9th circuit, but Trump isn\'t exactly Obama and is not going to dance to Apple\'s tune. Apple needs spanking and needs to understand that it\'s not…',
  },
  {
    id: '0004',
    author: 'Alan Friedman',
    title: 'Qualcomm says Apple\'s iOS update fix shouldn\'t prevent US ban on the iPhone - Phone Arena',
    description: 'Qualcomm filed a document with the U.S. ITC that says Apple\'s iOS workaround that removes any trace of unlicensed Qualcomm IP should not prevent the ITC from banning the sales and imports of certai...',
    url: 'https://bloximages.newyork1.vip.townnews.com/richmond.com/content/tncms/assets/v3/editorial/0/de/0de6865d-274b-58a8-a726-863c20ab47d8/5c6c96de53ee2.image.jpg?resize=430%2C284",',
    urlToImage: '//i-cdn.phonearena.com/images/article/113823-two/Qualcomm-says-Apples-iOS-update-fix-shouldnt-prevent-U.S.-ban-on-the-iPhone.jpg',
    publishedAt: '2019-02-20T00:00:00Z',
    content: 'Apple has a history of disobeying court orders (eg, the UK case against Samsung). Apple probably think it owns the 9th circuit, but Trump isn\'t exactly Obama and is not going to dance to Apple\'s tune. Apple needs spanking and needs to understand that it\'s not…',
  },
];
